SOME_QUERY=\
    SELECT 'A', 'B' FROM DUMMY UNION SELECT 'C', 'D' FROM DUMMY

CREATE_SSP_TABLES=\
DO BEGIN \
    CREATE TABLE SSP_NODES (ID INTEGER UNIQUE NOT NULL, NAME NVARCHAR(255)); \
    INSERT INTO SSP_NODES VALUES (1, 'Schere'); \
    INSERT INTO SSP_NODES VALUES (2, 'Stein'); \
    INSERT INTO SSP_NODES VALUES (3, 'Papier'); \
    INSERT INTO SSP_NODES VALUES (4, 'Hulk'); \
    CREATE TABLE SSP_EDGES (ID INTEGER UNIQUE NOT NULL, SOURCE_ID INTEGER NOT NULL, SINK_ID INTEGER NOT NULL); \
    INSERT INTO SSP_EDGES VALUES (1, 1, 3); \
    INSERT INTO SSP_EDGES VALUES (2, 2, 1); \
    INSERT INTO SSP_EDGES VALUES (3, 3, 2); \
    INSERT INTO SSP_EDGES VALUES (4, 4, 1); \
    INSERT INTO SSP_EDGES VALUES (5, 4, 2); \
    INSERT INTO SSP_EDGES VALUES (6, 4, 3); \
END

CREATE_SSP_WORKSPACE=\
    CREATE GRAPH WORKSPACE SSP \
        EDGE TABLE SSP_EDGES \
            SOURCE COLUMN SOURCE_ID \
            TARGET COLUMN SINK_ID \
            KEY COLUMN ID \
        VERTEX TABLE SSP_NODES \
        KEY COLUMN ID; \

CREATE_FLIGHTS_TABLES=\
DO BEGIN \
    CREATE TABLE "FLIGHTS_NODES" ( \
        "NODE_KEY" NVARCHAR(100) PRIMARY KEY, \
        "TYPE"     NVARCHAR(100), \
        "NAME"     NVARCHAR(100), \
        "CITY"     NVARCHAR(100), \
        "COUNTRY"  NVARCHAR(100), \
        "LOCATION" ST_GEOMETRY(4326) \
    ); \
    CREATE TABLE "FLIGHTS_EDGES" ( \
        "EDGE_KEY" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, \
        "SOURCE" NVARCHAR(100) NOT NULL REFERENCES "FLIGHTS_NODES" ("NODE_KEY") \
            ON UPDATE CASCADE ON DELETE CASCADE, \
        "TARGET" NVARCHAR(100) NOT NULL REFERENCES "FLIGHTS_NODES" ("NODE_KEY") \
            ON UPDATE CASCADE ON DELETE CASCADE, \
        "DIST_KM" DOUBLE \
    ); \
END

INSERT_FLIGHTS_TABLES_VALUES=\
DO BEGIN \
    INSERT INTO "FLIGHTS_NODES" VALUES ( \
        'FRA', 'Airport', 'Frankfurt am Main Airport', 'Frankfurt am Main', 'Germany', \
        ST_GEOMFROMTEXT('POINT(8.570556 50.033333)', 4326)); \
    INSERT INTO "FLIGHTS_NODES" VALUES ( \
        'JFK', 'Airport', 'John F Kennedy International Airport', 'New York', 'United States', \
        ST_GEOMFROMTEXT('POINT(-73.77890015 -73.77890015)', 4326)); \
    INSERT INTO "FLIGHTS_NODES" VALUES ( \
        'DXB', 'Airport', 'Dubai International Airport', 'Dubai', 'United Arab Emirates', \
        ST_GEOMFROMTEXT('POINT(55.3643989563 25.2527999878)', 4326)); \
    INSERT INTO "FLIGHTS_NODES" VALUES ( \
        'AMS', 'Airport', 'Amsterdam Airport Schiphol', 'Amsterdam', 'Netherlands', \
        ST_GEOMFROMTEXT('POINT(4.76389 52.308601)', 4326)); \
    INSERT INTO "FLIGHTS_NODES" VALUES ( \
        'PEK', 'Airport', 'Beijing Capital International Airport', 'Beijing', 'China', \
        ST_GEOMFROMTEXT('POINT(116.58499908447266 40.080101013183594)', 4326)); \
    INSERT INTO "FLIGHTS_NODES" VALUES ( \
        'DEL', 'Airport', 'Indira Gandhi International Airport', 'Delhi', 'India', \
        ST_GEOMFROMTEXT('POINT(77.103104 28.5665)', 4326)); \
    INSERT INTO "FLIGHTS_NODES" VALUES ( \
        'PHL', 'Airport', 'Philadelphia International Airport', 'Philadelphia', 'United States', \
        ST_GEOMFROMTEXT('POINT(-75.24109649658203 -75.24109649658203)', 4326)); \
    INSERT INTO "FLIGHTS_NODES" VALUES ( \
        'TNA', 'Airport', 'Yaoqiang Airport', 'Jinan', 'China', \
        ST_GEOMFROMTEXT('POINT(117.21600341796875 36.857200622558594)', 4326)); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('FRA','PEK',7808.278); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('DEL','FRA',6131.81); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('JFK','FRA',6206.163); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('PEK','FRA',7808.278); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('AMS','FRA',367.268); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('DXB','FRA',4848.058); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('FRA','JFK',6206.163); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('JFK','AMS',5863.339); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('PEK','AMS',7848.339); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('DXB','AMS',5174.013); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('DEL','AMS',6375.078); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('FRA','AMS',367.268); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('FRA','DXB',4848.058); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('FRA','DEL',6131.81); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('DEL','PEK',3815.291); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('DXB','PEK',5855.097); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('AMS','PEK',7848.339); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('DEL','DXB',2187.214); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('PEK','DXB',5855.097); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('AMS','DXB',5174.013); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('JFK','DXB',11021.831); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('DEL','JFK',11776.798); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('AMS','JFK',5863.339); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('DXB','JFK',11021.831); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('AMS','DEL',6375.078); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('PEK','DEL',3815.291); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('DXB','DEL',2187.214); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('JFK','DEL',11776.798); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('PHL','JFK',150.81); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('JFK','PHL',150.81); \
    INSERT INTO "FLIGHTS_EDGES" ("SOURCE", "TARGET", "DIST_KM") VALUES ('PEK','TNA',361.969); \
END

CREATE_FLIGHTS_WORKSPACE=\
    CREATE GRAPH WORKSPACE "FLIGHTS" \
        EDGE TABLE "FLIGHTS_EDGES" \
            SOURCE COLUMN "SOURCE" \
            TARGET COLUMN "TARGET" \
            KEY COLUMN "EDGE_KEY" \
        VERTEX TABLE "FLIGHTS_NODES" \
            KEY COLUMN "NODE_KEY"

SET_SCHEMA=\
    SET SCHEMA "%s"

DROP_SCHEMA_CASCADE=\
    DROP SCHEMA "%s" CASCADE

COUNT_RECORDS=\
    SELECT COUNT(*) FROM "%s"."%s"

GENERIC_SELECT_PROJECTION=\
    SELECT %s FROM "%s"."%s"